apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
replicas: 6
selector: 
  matchLabels:
    labels:
      app: backend
  spec:
    containers:
