FROM python:

ENV PYTHONDONTWRITEBYTECODE
ENV PYTHONUNBUFFERED

WORKDIR /productdeliveryApp

COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
CMD ["gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
